
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true

# POSTGRESQL SETTINGS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ascarnew_db
    username: ascarnew_user
    password: ascarnew_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.format_sql]': true

# ORACLE SETTINGS
# spring:
#   datasource:
#     url: jdbc:oracle:thin:@localhost:1521/contactlist_db
#     username: contactlist_user
#     password: 12345
#     driver-class-name: oracle.jdbc.OracleDriver
#   jpa:
#     show-sql: true
#     database-platform: org.hibernate.dialect.Oracle12cDialect
#     hibernate:
#       ddl-auto: update
#     properties:
#       format-sql: true

ascarrent:
  app:
    jwtSecret: ascar@Rent@3414
    jwtExpirationMs: 86400000

#image
servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB

logging:
  file:
    name: logs/ascarrent.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[ascarrent]': DEBUG

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true



info:
  application:
    name: 'As Car Rent Backend Application'
    description: 'This is Contact List Backend App developed by Feridun OZCELIK'
    version: '@project.version@'

